/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author thanh
 */
public class NhaCCForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form NccForm
     */
    public NhaCCForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        Them = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        Sua = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        XuatEx = new javax.swing.JButton();
        NhapEx = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LuaChon = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        Refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNCC = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jToolBar1.setFloatable(true);
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(371, 91));

        Them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        Them.setText("Thêm");
        Them.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Them.setFocusable(false);
        Them.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Them.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(Them);

        Xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        Xoa.setText("Xóa");
        Xoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Xoa.setFocusable(false);
        Xoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Xoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(Xoa);

        Sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fix.png"))); // NOI18N
        Sua.setText("Sửa");
        Sua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sua.setFocusable(false);
        Sua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(Sua);
        jToolBar1.add(jSeparator1);

        XuatEx.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        XuatEx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/export ex.png"))); // NOI18N
        XuatEx.setText("Xuất Excel");
        XuatEx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XuatEx.setFocusable(false);
        XuatEx.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        XuatEx.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(XuatEx);

        NhapEx.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NhapEx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/import ex.png"))); // NOI18N
        NhapEx.setText("Nhập Excel");
        NhapEx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NhapEx.setFocusable(false);
        NhapEx.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NhapEx.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(NhapEx);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 320, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LuaChon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LuaChon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(LuaChon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 40));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 360, 40));

        Refresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        Refresh.setText("Làm mới");
        Refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel2.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 140, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 770, 100));

        jScrollPane1.setBorder(null);

        tblNCC.setFont(new java.awt.Font("SF Pro Display", 0, 15)); // NOI18N
        tblNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã NCC", "Tên nhà cung cấp", "Số điện thoại", "Địa chỉ"
            }
        ));
        jScrollPane1.setViewportView(tblNCC);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1160, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LuaChon;
    private javax.swing.JButton NhapEx;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Sua;
    private javax.swing.JButton Them;
    private javax.swing.JButton Xoa;
    private javax.swing.JButton XuatEx;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblNCC;
    // End of variables declaration//GEN-END:variables
}
