/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author thanh
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        NhaCC = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SanPham = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NhapHang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PhieuNhap = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        XuatHang = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PhieuXuat = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TonKho = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TaiKhoan = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ThongKe = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        DoiThongTin = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        DangXuat = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý kho máy tính");
        setPreferredSize(new java.awt.Dimension(1420, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.setPreferredSize(new java.awt.Dimension(240, 730));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NhaCC.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        NhaCC.setPreferredSize(new java.awt.Dimension(244, 40));

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NhaCC.png"))); // NOI18N
        jLabel1.setText("NHÀ CUNG CẤP");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout NhaCCLayout = new javax.swing.GroupLayout(NhaCC);
        NhaCC.setLayout(NhaCCLayout);
        NhaCCLayout.setHorizontalGroup(
            NhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhaCCLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        NhaCCLayout.setVerticalGroup(
            NhaCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhaCCLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        Menu.add(NhaCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, -1));

        SanPham.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        SanPham.setPreferredSize(new java.awt.Dimension(244, 40));

        jLabel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SanPham.png"))); // NOI18N
        jLabel2.setText("SẢN PHẨM");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout SanPhamLayout = new javax.swing.GroupLayout(SanPham);
        SanPham.setLayout(SanPhamLayout);
        SanPhamLayout.setHorizontalGroup(
            SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SanPhamLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        SanPhamLayout.setVerticalGroup(
            SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SanPhamLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        Menu.add(SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 40));

        NhapHang.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        NhapHang.setPreferredSize(new java.awt.Dimension(244, 40));

        jLabel3.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NhapHang.png"))); // NOI18N
        jLabel3.setText("NHẬP HÀNG");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout NhapHangLayout = new javax.swing.GroupLayout(NhapHang);
        NhapHang.setLayout(NhapHangLayout);
        NhapHangLayout.setHorizontalGroup(
            NhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhapHangLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        NhapHangLayout.setVerticalGroup(
            NhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhapHangLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        Menu.add(NhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 40));

        PhieuNhap.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        PhieuNhap.setPreferredSize(new java.awt.Dimension(244, 40));

        jLabel5.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/phieunhap.png"))); // NOI18N
        jLabel5.setText("PHIẾU NHẬP");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout PhieuNhapLayout = new javax.swing.GroupLayout(PhieuNhap);
        PhieuNhap.setLayout(PhieuNhapLayout);
        PhieuNhapLayout.setHorizontalGroup(
            PhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhieuNhapLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        PhieuNhapLayout.setVerticalGroup(
            PhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhieuNhapLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        Menu.add(PhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 40));

        XuatHang.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        XuatHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XuatHang.setPreferredSize(new java.awt.Dimension(244, 40));

        jLabel6.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xuathang.png"))); // NOI18N
        jLabel6.setText("XUẤT HÀNG");

        javax.swing.GroupLayout XuatHangLayout = new javax.swing.GroupLayout(XuatHang);
        XuatHang.setLayout(XuatHangLayout);
        XuatHangLayout.setHorizontalGroup(
            XuatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XuatHangLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        XuatHangLayout.setVerticalGroup(
            XuatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XuatHangLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        Menu.add(XuatHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 250, 40));

        PhieuXuat.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        PhieuXuat.setPreferredSize(new java.awt.Dimension(244, 40));

        jLabel7.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/phieuxuat.png"))); // NOI18N
        jLabel7.setText("PHIẾU XUẤT");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout PhieuXuatLayout = new javax.swing.GroupLayout(PhieuXuat);
        PhieuXuat.setLayout(PhieuXuatLayout);
        PhieuXuatLayout.setHorizontalGroup(
            PhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhieuXuatLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        PhieuXuatLayout.setVerticalGroup(
            PhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhieuXuatLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        Menu.add(PhieuXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 40));

        TonKho.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        TonKho.setPreferredSize(new java.awt.Dimension(244, 40));

        jLabel8.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tonkho.png"))); // NOI18N
        jLabel8.setText("TỒN KHO");

        javax.swing.GroupLayout TonKhoLayout = new javax.swing.GroupLayout(TonKho);
        TonKho.setLayout(TonKhoLayout);
        TonKhoLayout.setHorizontalGroup(
            TonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TonKhoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        TonKhoLayout.setVerticalGroup(
            TonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TonKhoLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        Menu.add(TonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 250, 40));

        TaiKhoan.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        TaiKhoan.setPreferredSize(new java.awt.Dimension(244, 40));

        jLabel9.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/taikhoan.png"))); // NOI18N
        jLabel9.setText("TÀI KHOẢN");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout TaiKhoanLayout = new javax.swing.GroupLayout(TaiKhoan);
        TaiKhoan.setLayout(TaiKhoanLayout);
        TaiKhoanLayout.setHorizontalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        TaiKhoanLayout.setVerticalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        Menu.add(TaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 250, 40));

        ThongKe.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        ThongKe.setPreferredSize(new java.awt.Dimension(244, 40));

        jLabel10.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongke.png"))); // NOI18N
        jLabel10.setText("THỐNG KÊ");

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        Menu.add(ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 250, 40));

        DoiThongTin.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        DoiThongTin.setPreferredSize(new java.awt.Dimension(244, 40));

        jLabel11.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongtin.png"))); // NOI18N
        jLabel11.setText("ĐỔI THÔNG TIN");

        javax.swing.GroupLayout DoiThongTinLayout = new javax.swing.GroupLayout(DoiThongTin);
        DoiThongTin.setLayout(DoiThongTinLayout);
        DoiThongTinLayout.setHorizontalGroup(
            DoiThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoiThongTinLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        DoiThongTinLayout.setVerticalGroup(
            DoiThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoiThongTinLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        Menu.add(DoiThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 250, 40));

        DangXuat.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        DangXuat.setPreferredSize(new java.awt.Dimension(244, 40));

        jLabel12.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dangxuat.png"))); // NOI18N
        jLabel12.setText("ĐĂNG XUẤT");

        javax.swing.GroupLayout DangXuatLayout = new javax.swing.GroupLayout(DangXuat);
        DangXuat.setLayout(DangXuatLayout);
        DangXuatLayout.setHorizontalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuatLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel12)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        DangXuatLayout.setVerticalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuatLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        Menu.add(DangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 250, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Konichiwa");
        Menu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, 50));

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 760));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        getContentPane().add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1180, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel DangXuat;
    private javax.swing.JPanel DoiThongTin;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel NhaCC;
    private javax.swing.JPanel NhapHang;
    private javax.swing.JPanel PhieuNhap;
    private javax.swing.JPanel PhieuXuat;
    private javax.swing.JPanel SanPham;
    private javax.swing.JPanel TaiKhoan;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JPanel TonKho;
    private javax.swing.JPanel XuatHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
